### ISSUE TITLE
Robochrome not exporting

### ISSUE THREAD

**Issue by matterofsorts** [jenskutilek/RoboChrome#5] opened 2020-02-26 00:56 UTC
Hi Jens,

I’m having an issue exporting fonts with Robochrome. I downloaded the latest (0.7.3) through Mechanic and I’m running Robofont 3.3 (1911061105) on Mojave (10.14.3).

After adding a color palette (the default black and black again at 50%) and assigning color layers to base glyphs, I exported a standard OTF with Robofont and then tried generating a SVG.

Robochrome stalls at Rendering SVG and I get the traceback:

Exporting SVG format with palette 1 ...
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 500, in action_
    self.callback(sender)
  File "RoboChrome.py", line 170, in _choose_file_to_export
  File "RoboChrome.py", line 180, in _export_to_font
  File "/Users/vc/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 346, in export_to_otf
    self._export_svg(otfpath, palette_index, parent_window)
  File "/Users/vc/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 428, in _export_svg
    red   = int(_palette[i][1:3], 16)
TypeError: 'NSCachedColorSpaceColor' object is not subscriptable
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 95, in sendEvent_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 500, in action_
    self.callback(sender)
  File "RoboChrome.py", line 170, in _choose_file_to_export
  File "RoboChrome.py", line 180, in _export_to_font
  File "/Users/vc/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 346, in export_to_otf
    self._export_svg(otfpath, palette_index, parent_window)
  File "/Users/vc/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 428, in _export_svg
    red   = int(_palette[i][1:3], 16)
TypeError: 'NSCachedColorSpaceColor' object is not subscriptable

Do you have any clues on fixing this?

Thanks so much.

<img width="612" alt="Screen Shot 2020-02-26 at 11 54 09 am" src="https://user-images.githubusercontent.com/23010824/75301380-c1e78f80-588e-11ea-9faa-246a05fbb6de.png">

**Comment by jenskutilek** [comment] 2020-02-28 10:51
Hm, I can't reproduce, but I have only RF 3.4 beta to test at the moment. Could you send me your ufo to …@….de so I can test?

**Comment by jenskutilek** [comment] 2020-03-08 09:38
I think I have a solution. But I have to test some more before I can upload it.

Until then, could you try this? After adding the palette and colours, close the RoboChrome window and open it again. That should cause the color values to be converted to hex-RGB values, and the export should work.

**Comment by matterofsorts** [comment] 2020-03-08 10:11
Hi Jens,

Thanks for the assistance. Yes closing and reopening seems to fix the export issue though when closing the RoboChrome window I get the following traceback:

Traceback (most recent call last):
​  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/vanilla/vanillaWindows.py", line 579, in windowWillClose_
    self._alertBindings("close")
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/vanilla/vanillaWindows.py", line 571, in _alertBindings
    value = callback(self)
  File "RoboChrome.py", line 672, in windowCloseCallback
  File "RoboChrome.py", line 589, in _paletteWriteToColorFont
  File "/Users/vc/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 578, in save_to_rfont
    self._save_key_to_lib(propkey, getattr(self, propkey))
  File "/Users/vc/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 613, in _save_key_to_lib
    self.rfont.lib["%s.%s" % (self.libkey, name)] = value
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/fontParts/base/lib.py", line 190, in __setitem__
    super(BaseLib, self).__setitem__(key, items)
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/fontParts/base/base.py", line 334, in __setitem__
    value = self.valueNormalizer.__func__(value)
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/fontParts/base/normalizers.py", line 240, in normalizeLibValue
    normalizeLibValue(v)
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/fontParts/base/normalizers.py", line 243, in normalizeLibValue
    normalizeLibKey(k)
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/fontParts/base/normalizers.py", line 223, in normalizeLibKey
    % type(value).__name__)
TypeError: Lib key must be a string, not int.
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 95, in sendEvent_
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/vanilla/vanillaWindows.py", line 579, in windowWillClose_
    self._alertBindings("close")
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/vanilla/vanillaWindows.py", line 571, in _alertBindings
    value = callback(self)
  File "RoboChrome.py", line 672, in windowCloseCallback
  File "RoboChrome.py", line 589, in _paletteWriteToColorFont
  File "/Users/vc/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 578, in save_to_rfont
    self._save_key_to_lib(propkey, getattr(self, propkey))
  File "/Users/vc/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/colorfont/__init__.py", line 613, in _save_key_to_lib
    self.rfont.lib["%s.%s" % (self.libkey, name)] = value
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/fontParts/base/lib.py", line 190, in __setitem__
    super(BaseLib, self).__setitem__(key, items)
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/fontParts/base/base.py", line 334, in __setitem__
    value = self.valueNormalizer.__func__(value)
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/fontParts/base/normalizers.py", line 240, in normalizeLibValue
    normalizeLibValue(v)
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/fontParts/base/normalizers.py", line 243, in normalizeLibValue
    normalizeLibKey(k)
  File "/Applications/RoboFont_3-3.app/Contents/Resources/lib/python3.7/fontParts/base/normalizers.py", line 223, in normalizeLibKey
    % type(value).__name__)
TypeError: Lib key must be a string, not int.

This doesn’t affect the exported font however, just a detail I thought you’d want to know (did you see this error in the RF 3.4 beta?)

It seems like when I choose a color with an opacity, it is lost on export (a 30% black is converted to 100% black on export). Is this related to the conversion of colors to a hex-RGB value? Is it possible to include an alpha channel?

Thanks again for your help!

**Comment by jenskutilek** [comment] 2020-03-08 13:39
I think the string/int problem is fixed already. If you are using the RF3.4 beta, you can try the https://github.com/jenskutilek/RoboChrome/tree/rf-3.4 branch (the API of the color cells has changed between 3.3 and 3.4).

**Comment by matterofsorts** [comment] 2020-03-09 10:16
Thanks Jens. I tried opening the rf-3.4 branch RoboChrome (0.7.5) using Robofont 3.4b (build 1912071454) and I get this traceback:

Traceback (most recent call last):
​  File "RoboChrome.py", line 920, in <module>
  File "lib/scripting/nameSpaceCallbacks.pyc", line 51, in OpenWindow
  File "RoboChrome.py", line 35, in __init__
  File "/Users/vc/Library/Application Support/RoboFont/plugins/RoboChrome.roboFontExt/lib/RoboChromeUI.py", line 61, in get_ui
TypeError: Use class methods to instantiate new Objective-C objects

**Comment by jenskutilek** [comment] 2020-03-11 14:11
Could you try the latest version from the master branch now? Everything should work there.

The rf3.4 branch may not work in your beta version yet, I tested it in the latest beta and things may have changed from your beta. Better to stay with the released versions…

**Comment by matterofsorts** [comment] 2020-03-17 03:06
Hi Jens. Thanks for the update. I updated Robochrome through Mechanic and ran it on the latest RF release. Almost everything works now! 

— Firstly, when I open an UFO with a previously defined palette, Robochrome seems to forget the defined colors giving me the error:

Missing color index in palette 0: 1 (in glyph /A)
Missing color index in palette 0: 0 (in glyph /A.layer00)

— Secondly, and more importantly, it can‘t seem to get transparent colors to work. I’ve just WeTransferred you a screencast of a font with two colors, Black and Black at 23% opacity. After exporting and installing the SVG, InDesign renders the transparent all shapes at 100% Black. Any clues why this might be?

Thanks again for your work!

**Comment by jenskutilek** [comment] 2020-04-14 19:25
Fixed now! Thanks.

**Closed as completed by jenskutilek** 2020-04-14 19:25 UTC
